services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - game

  auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth:/app
    ports:
      - "4000:4000"
    environment:
      - SERVICE_NAME=auth

  game:
    build: ./backend/game
    volumes:
      - ./backend/game:/app
    ports:
      - "4001:4001"
    environment:
      - SERVICE_NAME=game

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth
      - game

  logstash:
    build: ./elk/logstash
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/auth:/var/log/app
    ports:
      - "5044:5044"
    depends_on:
      - auth
      - game

  kibana:
    image: kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs:ro
    depends_on:
      - elasticsearch
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    volumes:
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./certs/instance:/usr/share/elasticsearch/config/certs/instance:ro
      - ./certs/ca:/usr/share/elasticsearch/config/certs/ca:ro
      - esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "4242"

      xpack.security.http.ssl.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - ft_transcendance_default


volumes:
  esdata:
